apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://lecture-08-01-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
